DATASET:
  dataset: "ADE20K"
  root_dataset: "./Data/ADE20K"
  list_train: "./Data/ADE20K/training.odgt"
  list_val: "./Data/ADE20K/validation.odgt"
  num_class: 150
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet18dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 512

TRAIN:
  # num_samples 20210
  batch_size_per_gpu: 4
  num_epoch: 20
  start_epoch: 7
  epoch_iters: 4000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True
  checkpoint: "epoch_10.pth"

TEST:
  checkpoint: "epoch_10.pth"
  result: "./"

DIR: "ckpt/ADE/ade20k-resnet18dilated-ppm_deepsup"
